# This prgram will poop or pee
import time
print('Hello I am the PoopeyBot')
time.sleep(1)
print('I want to pee/poop !!')
time.sleep(0.2)
print('...')
time.sleep(0.2)
print('....')
time.sleep(0.2)
print('.....')
time.sleep(0.2)
print('......')
time.sleep(0.2)
print('.......')
time.sleep(0.2)
print('........')
time.sleep(0.2)
print('.........')
time.sleep(0.2)
print('..........')
time.sleep(0.2)
print('...........')
time.sleep(0.2)
print('Should I pee or poop ?')
ToiletProject = input()
time.sleep(2)
if ToiletProject == 'pee':
    print('pssssssssssss...sssss...ssss...')
    time.sleep(1)
    print('*peeing*')
    time.sleep(1)
    print('Ahhhh it feels good to pee !')
else:
    print('*fart....fart.....fart...fart*')
    time.sleep(1)
    print('*splash*')
    time.sleep(1)
    print('Ahhhh it feels good to poop !')

if ToiletProject == 'poop':
    print('Long browntube ?')
    time.sleep(1)
    print('How long is browntube ?')
    time.sleep(1)
    browntube=input()
    print('VEEERY LONG MY FRIEND ' + browntube + '!!!')
else:
    print('How long is schlong ?')
    time.sleep(1)
    schlong=input()
    print('VEEERY LONG MY FRIEND ' + schlong + '!!!')


